=== 695215742/xmlcourse_landslide/views/music/music_list.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- 简易元素的定义 -->
	<xs:element name="music_list_name" type="xs:string"/>
	<xs:element name="creator" type="xs:string"/>
	<xs:element name="create_date" type="xs:string"/>
	<xs:element name="tag" type="xs:string"/>
	<xs:element name="description" type="xs:string"/>
	<xs:element name="music_list_booklet" type="xs:string"/>
	<xs:element name="booklet" type="xs:string"/>
	<xs:element name="artist_name" type="xs:string"/>
	<xs:element name="track_title" type="xs:string"/>
	<xs:element name="album_title" type="xs:string"/>
	<xs:element name="date" type="xs:date"/>
	<xs:element name="genre">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Alternative"/>
				<xs:enumeration value="Books &amp; Spoken"/>
				<xs:enumeration value="Blues/R&amp;B"/>
				<xs:enumeration value="Children’s Music"/>
				<xs:enumeration value="Classical"/>
				<xs:enumeration value="Country"/>
				<xs:enumeration value="Dance"/>
				<xs:enumeration value="Easy Listening"/>
				<xs:enumeration value="Electronic"/>
				<xs:enumeration value="Folk"/>
				<xs:enumeration value="House"/>
				<xs:enumeration value="Industrial"/>
				<xs:enumeration value="Techno"/>
				<xs:enumeration value="Trance"/>
				<xs:enumeration value="Hip Hop/Rap"/>
				<xs:enumeration value="Holiday"/>
				<xs:enumeration value="Jazz"/>
				<xs:enumeration value="New Age"/>
				<xs:enumeration value="Pop"/>
				<xs:enumeration value="Religious"/>
				<xs:enumeration value="Rock"/>
				<xs:enumeration value="Soundtrack"/>
				<xs:enumeration value="Unclassifiable"/>
				<xs:enumeration value="World"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="composer" type="xs:string"/>
	<xs:element name="track_number">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="total_tracks">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="comment" type="xs:string"/>
	<xs:element name="file_name" type="xs:string"/>
	<xs:element name="file_size">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="(([1-9][0-9]*)|[0]).[0-9]* MB"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="duration">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="(([1-9][0-9]*)|[0]):[0-9]{2}.[0-9]{3}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="sample_rate">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="(([1-9][0-9]*)|[0]) Hz"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="channels">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:pattern value="1|2"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="bitrate">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="(([1-9][0-9]*)|[0]) kbps"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<!-- 属性的定义 -->
	<xs:attribute name="id" type="xs:integer"/>
	<!-- 复合元素的定义 -->
	<xs:element name="metadata">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="artist_name"/>
				<xs:element ref="track_title"/>
				<xs:element ref="album_title"/>
				<xs:element ref="date"/>
				<xs:element ref="genre"/>
				<xs:element ref="composer"/>
				<xs:element ref="track_number"/>
				<xs:element ref="total_tracks"/>
				<xs:element ref="comment"/>
				<xs:element ref="booklet"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="general">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="file_name"/>
				<xs:element ref="file_size"/>
				<xs:element ref="duration"/>
				<xs:element ref="sample_rate"/>
				<xs:element ref="channels"/>
				<xs:element ref="bitrate"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="music">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="metadata"/>
				<xs:element ref="general"/>
			</xs:sequence>
			<xs:attribute ref="id" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="music_list_info">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="music_list_name"/>
				<xs:element ref="creator"/>
				<xs:element ref="create_date"/>
				<xs:element ref="tag"/>
				<xs:element ref="description"/>
				<xs:element ref="music_list_booklet"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="music_list">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="music_list_info"/>
				<xs:element ref="music" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== 695215742/xmlcourse_landslide/views/music/music_list.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="music_list.xslt"?>
<!--<?xml-stylesheet type="text/css" href="music_list.css"?>-->
<!--<!DOCTYPE music_list SYSTEM "music_list.dtd">
<music_list>-->
<music_list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="music_list.xsd">
	<music_list_info>
		<music_list_name>全球首张45转黑胶唱片问世</music_list_name>
		<creator>音乐百科</creator>
		<create_date>2015-03-30</create_date>
		<tag>经典好歌 流行 英语 致青春 宣泄</tag>
		<description>1949年3月31日，世界上首张每分钟45转的黑胶唱片发行。和多数人观念中黑胶唱片就是黑色不同，这张由RCA公司发行的乡村/西部歌手Eddy Arnold的单曲碟《Texarkana Baby》其实是用绿色的乙烯塑料制成的。在那个年代，黑胶唱片实际上通过不同的颜色来区分音乐的类别，红色的是古典音乐，黄色的则是儿童歌曲。黑胶唱片的规格中，对音质影响最大的就是转速了，初期技术条件不高，只能提高转速增长音轨来保证唱片的音质，当时黑胶唱片的转速标准被定为每分钟78转，这种黑胶唱片就被称为标准播放(Standard-Playing），简称“SP”，它每面只能记录5分钟左右的音频信息，随着技术的发展，一种每分钟45转的黑胶唱片问世了，因为它所记录的音频信息要比78转的唱片延长很多，因此被定义为延长播放（Extended Playing），简称为“EP”。
收回</description>
		<music_list_booklet>boy.jpg</music_list_booklet>
	</music_list_info>
	<music id="1">
		<metadata>
			<artist_name>Bon Jovi</artist_name>
			<track_title>shdjak</track_title>
			<album_title>It's My Life</album_title>
			<date>2015-02-19</date>
			<genre>Soundtrack</genre>
			<composer>Bon Jovi</composer>
			<track_number>1</track_number>
			<total_tracks>3</total_tracks>
			<comment>大学过的最辛苦的时候，和妹妹在金凤呈祥打工，每天这首歌都要听几十遍，听了一个多月。结果就是已经刻到骨子里了，也不是觉得多好听，但每次听到，都会发呆，想起以前一天打两份工，吃一星期白水挂面的日子。更提醒我要对妹妹好。这首歌，这辈子是忘不了了。。。</comment>
			<booklet>It's My Life.jpg</booklet>
		</metadata>
		<general>
			<file_name>It's My Life</file_name>
			<file_size>9.19 MB</file_size>
			<duration>4:00.960</duration>
			<sample_rate>44100 Hz</sample_rate>
			<channels>2</channels>
			<bitrate>320 kbps</bitrate>
		</general>
	</music>
	<music id="2">
		<metadata>
			<artist_name>Pitbull / Jennifer Lopez / Cláudia Leitte</artist_name>
			<track_title>Glassy Sky</track_title>
			<album_title>We Are One (Ole Ola) (The Official 2014 FIFA World Cup Song)</album_title>
			<date>2015-02-19</date>
			<genre>Soundtrack</genre>
			<composer>やまだ豊</composer>
			<track_number>2</track_number>
			<total_tracks>3</total_tracks>
			<comment>潘帕斯雄鹰是这届世界杯我最大的痛！！！2016再战～～Vamos Argentina ！！</comment>
			<booklet>We Are One.jpg</booklet>
		</metadata>
		<general>
			<file_name>We Are One (Ole Ola)</file_name>
			<file_size>11.2 MB</file_size>
			<duration>4:54.813</duration>
			<sample_rate>44100 Hz</sample_rate>
			<channels>2</channels>
			<bitrate>320 kbps</bitrate>
		</general>
	</music>
	<music id="3">
		<metadata>
			<artist_name>やまだ豊</artist_name>
			<track_title>TG Symphonie</track_title>
			<album_title>TVアニメ「東京喰種」オリジナル・サウンドトラック - EP</album_title>
			<date>2015-02-19</date>
			<genre>Soundtrack</genre>
			<composer>やまだ豊</composer>
			<track_number>3</track_number>
			<total_tracks>3</total_tracks>
			<comment>少年清澈，少年欢乐</comment>
			<booklet>What Makes You Beautiful.jpg</booklet>
		</metadata>
		<general>
			<file_name>What Makes You Beautiful</file_name>
			<file_size>16.2 MB</file_size>
			<duration>7:05.413</duration>
			<sample_rate>44100 Hz</sample_rate>
			<channels>2</channels>
			<bitrate>320 kbps</bitrate>
		</general>
	</music>
</music_list>

=== 695215742/xmlcourse_landslide/views/music/tmp0000.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="music_list.xslt"?>
<!--<?xml-stylesheet type="text/css" href="music_list.css"?>-->
<!--<!DOCTYPE music_list SYSTEM "music_list.dtd">
<music_list>-->
<music_list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="music_list.xsd">
	<music_list_info>
		<music_list_name>全球首张45转黑胶唱片问世</music_list_name>
		<creator>音乐百科</creator>
		<create_date>2015-03-30</create_date>
		<tag>经典好歌 流行 英语 致青春 宣泄</tag>
		<description>1949年3月31日，世界上首张每分钟45转的黑胶唱片发行。和多数人观念中黑胶唱片就是黑色不同，这张由RCA公司发行的乡村/西部歌手Eddy Arnold的单曲碟《Texarkana Baby》其实是用绿色的乙烯塑料制成的。在那个年代，黑胶唱片实际上通过不同的颜色来区分音乐的类别，红色的是古典音乐，黄色的则是儿童歌曲。黑胶唱片的规格中，对音质影响最大的就是转速了，初期技术条件不高，只能提高转速增长音轨来保证唱片的音质，当时黑胶唱片的转速标准被定为每分钟78转，这种黑胶唱片就被称为标准播放(Standard-Playing），简称“SP”，它每面只能记录5分钟左右的音频信息，随着技术的发展，一种每分钟45转的黑胶唱片问世了，因为它所记录的音频信息要比78转的唱片延长很多，因此被定义为延长播放（Extended Playing），简称为“EP”。虽然今天黑胶唱片已经没有往日那么风光，但是重温这些曾在黑胶时代创下至少超过两千万张销量的经典专辑，你还是能被它实实在在的魅力打动。
收回</description>
		<music_list_booklet>1.jpg</music_list_booklet>
	</music_list_info>
	<music id="1">
		<metadata>
			<artist_name>やまだ豊</artist_name>
			<track_title>On My Own</track_title>
			<album_title>TVアニメ「東京喰種」オリジナル・サウンドトラック - EP</album_title>
			<date>2015-02-19</date>
			<genre>Soundtrack</genre>
			<composer>やまだ豊</composer>
			<track_number>1</track_number>
			<total_tracks>3</total_tracks>
			<comment>很棒的音乐</comment>
			<booklet>Booklet 01.jpg</booklet>
		</metadata>
		<general>
			<file_name>On My Own.mp3</file_name>
			<file_size>9.19 MB</file_size>
			<duration>4:00.960</duration>
			<sample_rate>44100 Hz</sample_rate>
			<channels>2</channels>
			<bitrate>320 kbps</bitrate>
		</general>
	</music>
	<music id="2">
		<metadata>
			<artist_name>やまだ豊</artist_name>
			<track_title>Glassy Sky</track_title>
			<album_title>TVアニメ「東京喰種」オリジナル・サウンドトラック - EP</album_title>
			<date>2015-02-19</date>
			<genre>Soundtrack</genre>
			<composer>やまだ豊</composer>
			<track_number>2</track_number>
			<total_tracks>3</total_tracks>
			<comment/>
			<booklet>Booklet 01.jpg</booklet>
		</metadata>
		<general>
			<file_name>Glassy Sky.mp3</file_name>
			<file_size>11.2 MB</file_size>
			<duration>4:54.813</duration>
			<sample_rate>44100 Hz</sample_rate>
			<channels>2</channels>
			<bitrate>320 kbps</bitrate>
		</general>
	</music>
	<music id="3">
		<metadata>
			<artist_name>やまだ豊</artist_name>
			<track_title>TG Symphonie</track_title>
			<album_title>TVアニメ「東京喰種」オリジナル・サウンドトラック - EP</album_title>
			<date>2015-02-19</date>
			<genre>Soundtrack</genre>
			<composer>やまだ豊</composer>
			<track_number>3</track_number>
			<total_tracks>3</total_tracks>
			<comment/>
			<booklet>Booklet 01.jpg</booklet>
		</metadata>
		<general>
			<file_name>TG Symphonie.mp3</file_name>
			<file_size>16.2 MB</file_size>
			<duration>7:05.413</duration>
			<sample_rate>44100 Hz</sample_rate>
			<channels>2</channels>
			<bitrate>320 kbps</bitrate>
		</general>
	</music>
</music_list>
