=== 695215742/xmlcourse_landslide/views/music/music_group.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2015 rel. 3 (x64) (http://www.altova.com) by 123 (123) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="logo" type="xs:string"/>
	<xs:element name="stuID" type="xs:string"/>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="email">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="[a-zA-Z0-9]*@[a-zA-Z0-9]*.[a-zA-Z0-9]*.[a-zA-Z0-9]*"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="description" type="xs:string"/>
	<xs:element name="member">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="stuID"/>
				<xs:element ref="name"/>
				<xs:element ref="email"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="members">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="member" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="music_group">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="logo"/>
				<xs:element ref="members"/>
				<xs:element ref="description"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== 695215742/xmlcourse_landslide/views/music/music_group.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="music_group.xslt"?>
<music_group xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="music_group.xsd">
	<logo>justMusic.png</logo>
	<members>
		<member>
			<stuID>71Y12124</stuID>
			<name>蒋志远</name>
			<email>1130404934@qq.com</email>
		</member>
		<member>
			<stuID>71Y12126</stuID>
			<name>陈冰阳</name>
			<email>eretion@vip.qq.com</email>
		</member>
	</members>
	<description>
		我们负责对于音乐信息模块进行编写,
		蒋志远负责css样式编写以及xstl的转化,
		陈冰阳负责fo文件的编写以及Pdf的转化.
	</description>
</music_group>
